version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gearguard_db
    restart: always
    environment:
      - POSTGRES_USER=gearguard_user
      - POSTGRES_PASSWORD=gearguard_password
      - POSTGRES_DB=gearguard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
